# -*- coding: utf-8 -*-
"""User_input.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18VTv9DApamFkMJPv4Eo2WC1Q-V0AlCDw
"""

# user_input.py

# Ask the user for their name and store it in the variable "name"
name = ("Jostina ")

# Ask the user for their age and store it in the variable "age"
age = ("32 ")

# Ask the user for their location and store it in the variable "location"
location = ("Mombasa Road ")

# Print out a personalized message using the user's name, age, and location
print(f"Hello {name}, you are {age} years old and live in {location}.")